apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::162346212712:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-19DVTODGX65ZG
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::162346212712:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-28T03:35:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "10051"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: bc7a9d33-b7e4-4e1a-8370-290badd50e6c
